Dydx:
  Network:
    host: https://api.stage.dydx.exchange
    chainID: 5
  User:
    limitFee: 0.2
Perpetual:
  Network:
    host: https://mainnet.optimism.io/
  User:
    slippage: 0.05
GMX:
  Network:
    host: https://arbitrum.llamarpc.com # https://arbitrum-goerli.public.blastapi.io

